### ISSUE TITLE
I'm encountering an issue while running colcon build on my system. The system seems to freeze during the build process.

### ISSUE THREAD

**Issue by kyan20105** [Mechazo11/ros2_orb_slam3#4]
I'm currently using Ubuntu 22.04 with ROS2 Humble. I have followed all the necessary steps and double-checked them multiple times. However, whenever I run colcon build --symlink-install, my system freezes.
What I have done for ros2_orb_slam3
mkdir -p ~/ros2_test/src
cd ~/ros2_test/src
git clone https://github.com/Mechazo11/ros2_orb_slam3.git
cd .. [make sure you are in ~/ros2_ws root directory]
source /opt/ros/humble/setup.bash
colcon build --symlink-install
I run colcon build --symlink-install, my system freezes

**Comment by Mechazo11** [comment]
Hi @kyan20105, can you try with just ```colon build``` command and report back whether the build freezes. How about creating a blank package and testing if the build freezes. If it is the latter, then it could be a problem with your ROS 2 Humble installation.

**Comment by kyan20105** [comment]
Hi @Mechazo11 . I've tried running colcon build, but my machine still hangs. I attempted to build it on a Raspberry Pi 4 with 4GB of RAM. After 2 minutes, it only reached 12% before hanging. Then, I tried it on my computer with 8GB of RAM. After 12 seconds, it only reached 40% before hanging. Both systems are running Ubuntu 22.04 and ROS2 Humble. The reason for the hang is likely due to running out of RAM. I suspect it could be due to missing or mismatched libraries causing this issue. Could you please confirm if these versions are compatible:
OpenCV 4.5.4

g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

pkg-config --modversion eigen3
3.4.0

cmake 3.22.1
Do I need to install additional libraries such as DBoW2, g2o, Sophus separately, or will they be automatically included when I run colcon build?

**Comment by Mechazo11** [comment]
@kyan20105 

I suspected the issue was with RAM.  Very recently I too faced this issue with both my Ubunut 22.04 laptop and desktop, both having 16Gb RAM and 2Gb swap. Once I set 8 Gb of swap ORB SLAM3 built just fine. In fact, my work version of ORB-SLAM3 contains many more libraries and is significantly bigger than the vanilla 1.0 version (which is the basis of this package) and that builds just fine with the settings I set for this package.

Please note, my port of ORB SLAM 3 was never tested on Rasbperby Pi 4 and as far I know, ORB SLAM3 wasn't really designed to run on such resource constrained hardware without significant modification to its internal architecture.

For the 2nd part of the question, OpenCV 4.5, Eigen 3.3, Cmake 3.22.1 should all be fine since I set in the ```CmakeLists.txt``` file, the following lines,

```
cmake_minimum_required(VERSION 3.8)
find_package(OpenCV 4.2 REQUIRED)
find_package(Eigen3 3.3.0 REQUIRED) # Matched with Sophus
```

And result of ```g++ --version``` from one of my Ubunut 22.04 machine that builds this package
```
g++ (Ubuntu 11.4.0-1ubuntu1-22-04) 11.4.0
```

Regarding the 3rd part of the question, kindly take a look into ```CmakeLists.txt``` file, you will see the ```orb_slam3_lib``` looks for prebuilt ``` .so``` files for DBoW2, g20 and Sophus that ships with the package. 

I will actually modify the README.md file to clarify what hardware I tested the package on to reduce further confusion for future users.

**Comment by kyan20105** [comment]
@Mechazo11 
Thank you for your assistance. I'll try to find a machine with higher RAM and conduct further tests

**Comment by Mechazo11** [comment]
@kyan20105 sounds good, I will be closing this issue now. Good luck.
